export default {
    LOGIN: 'employee_login',
    TAB_BAR_HOME: 'HOME',
    TAB_BAR_ROSTERS: 'ROSTER',
    TAB_BAR_SHIFTS: 'SHIFTS',
    TAB_BAR_ACTIONS: 'ACTIONS',
    TAB_BAR_MESSAGES: 'MESSAGES',
    ACTION_DETAILS: 'Action Details',
    ROSTER_CALENDAR: 'Rosters',
    PATROL:'Patrol',
    MAINTENANCE:'Maintenance',
    QRSCAN:'QR Scan',
    START_MANUAL_SHIFT :'Start Manual Shift',
    AUTO_SHIFT_START :'Start Shift',
    INTOXICATION:'Intoxication',
    CROWDCOUNT:'CrowdCount',
    SETTING:'Setting',
    BOAT_REPORT:'Boat Report',
    WELFARE_CHECK:'WelfareCheck',
    FIRE_ALARM :'Fire Alarm -1',
    FIRE_ALARM_1 :'Fire Alarm -2',
    VEHICLE_REPORT:'Vehicle Report',
    BOMB_THEART_STEP_1 :'Bomb Threat - 1',
    BOMB_THEART_STEP_2 :'Bomb Threat - 2',
    BOMB_THEART_STEP_3 :'Bomb Threat - 3',
    BOMB_THEART_STEP_4 :'Bomb Threat - 4',
    ARMED_HOLDUP_1:'Armed Holdup - 1',
    ARMED_HOLDUP_2:'Armed Holdup - 2',
    ARMED_HOLDUP_3:'Armed Holdup - 3',
    ARMED_HOLDUP_4:'Armed Holdup - 4',
    ACCIDENT_STEP_1:'Accident/Incident/Hazard -1',
    ACCIDENT_STEP_2:'Accident/Incident/Hazard -2',
    ACCIDENT_STEP_3:'Accident/Incident/Hazard -3',
    ACCIDENT_STEP_4:'Accident/Incident/Hazard -4',
    ACCIDENT_STEP_5:'Accident/Incident/Hazard -5',
    ACCIDENT_STEP_6:'Accident/Incident/Hazard -6',
    MESSAGE_DETAIL:'Message Detail',
    END_SHIFT:'End Shift',
    SHIFT_CODE:'Shift Code'
    
};
